title: Jamall Harris
tagline: 'Software Engineer'
url: 'https://jharri34.github.io'

email: harrisjayjamall@gmail.com

author:
  name: 'Jamall Harris'
  email: 'harrisjayjamall@gmail.com'
  phone: '404.910.2257'
description: >- # this means to ignore newlines until "baseurl:"
  Software engineer with strong Java skills, focused on building elegant, 
  innovative solutions that solve real-world problems. Passionate about learning, creating, 
  and making a positive impact.
social:
  name: Jamall Harris
  links: 
  - 'https://github.com/jharri34'
  - 'https://www.linkedin.com/in/jamall-harris-8a6a3952/'
social_links:
  github:  'https://github.com/jharri34'
  linkedin: 'https://www.linkedin.com/in/jamall-harris-8a6a3952/'
collections:
  portfolio:
    sort_by: 'end_date'
    output: true
    permalink: /portfolio/:title/
  skills:
    output: true
  projects:
    output: true
  
sass:
  sass_dir: _sass
  style: compressed

defaults:

  - scope:
      path: ""
    values:
      layout: "default"


# whitelisted plugins and themes  https://pages.github.com/versions/
plugins:
# included by jekyll tutorial
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # included by default by github pages according to https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
  - jekyll-coffeescript
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  

